accounts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('', home, name='home'),
]

borameboard/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'borame_board'

urlpatterns = [
    path('', views.index, name='index'),
    path('regist/', views.regist, name='regist'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('borame_board:index')),
    path('board/', include('borameboard.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

borameboard/models.py
from django.db import models
from django.contrib.auth.models import User


class Board(models.Model):
    title = models.CharField(max_length=200,verbose_name='멋쟁이 사자의 글 제목',help_text='* 제목은 최대 100자 이내')
    author = models.CharField(max_length=100, verbose_name='글쓴이')
    content = models.TextField(verbose_name='글 내용')
    published_date = models.DateTimeField(auto_now=True, verbose_name='등록(수정)일')

    
    
    def __str__(self):
        return self.title
    

# Create your models here.

borameboard/forms.py
from django import forms
from django.forms import widgets
from .models import Board

class RegistForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'author', 'content']  # '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

accounts/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
# 회원가입
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                                            username=request.POST['username'],
                                            password=request.POST['password1'],
                                            email=request.POST['email'],)
            auth.login(request, user)
            return redirect('/')
        return render(request, 'signup.html')
    return render(request, 'signup.html')

# 로그인
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            return render(request, 'login.html', {'error': '멋쟁이사자 회원이 아니거나 아이디, 비밀번호가 틀립니다.'})
    else:
        return render(request, 'login.html')


# 로그아웃
def logout(request):
    auth.logout(request)
    return redirect('/')

# home
def home(request):
    return render(request, 'home.html')

borameboard/views.py
from borameboard.models import Board
from django.shortcuts import render,redirect
from .models import Board
from .forms import RegistForm
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .forms import *
from .models import *
from django.contrib.auth.models import User

def index(request):
    page = request.GET.get('page', '1')  # 페이지 파라미터 얻기, 없으면 1
    board_list = Board.objects.order_by('-id')

    # 페이징 처리
    paginator = Paginator(board_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)  # page에 해당하는 페이징 객체 생성
    user = request.user
    context = {'board_list': page_obj,
               'user':user
               }   # 페이징 객체(page_obj) 전달
    return render(request, 'borameboard/index.html', context)



def regist(request):
    if request.method == 'POST':
        form = RegistForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('borame_board:index')
    else:
        form = RegistForm()
    context = {'form': form,
               'user': request.user}
    return render(request, 'borameboard/regist_form.html', context)

def detail(request, pk):
    board_list = get_object_or_404(Board, id=pk)
    context = {'board_list': board_list}
    return render(request, 'borameboard/detail.html', context)

def edit(request, pk):
    post = get_object_or_404(Board, id=pk)
    if request.method == 'POST':
        form = RegistForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('borame_board:index')
    else:
        form = RegistForm(instance=post)
    context = {'form': form,}
    return render(request, 'borameboard/edit_form.html', context)

def delete(request, pk):
    post = get_object_or_404(Board, id=pk)
    post.delete()
    return redirect('borame_board:index')

accounts/templates/login.html
{% block content %}
<div class="wrapper">
    <div style="text-align: center;">
        <h1>로그인</h1>
        <form method="POST">
            {% csrf_token %}
            아이디:
            <br>
            <input name="username" type="text">
            <br>
            비밀번호:
            <br>
            <input name="password" type="password">
            <br><br>
            <input type="submit" class="btn btn-primary" value="Login">
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% block content %}
<div class="wrapper" style="text-align: center;">
    <h1>회원가입</h1>
    <form method="POST">
        {% csrf_token %}
        아이디: <br>
        <input name="username" type="text">
        <br>
        비밀번호: <br>
        <input name="password1" type="password">
        <br>
        비밀번호 확인: <br>
        <input name="password2" type="password">
        <br>
        이메일: <br>
        <input name="email" type="email">
        <br><br>
        <input type="submit" class="btn btn-primary" value="Sign Up">
    </form>
</div>
{% endblock %}

accounts/templates/signup2.html
{% block content %} 
<div class="wrapper" style="text-align: center;"> 
	<h1>회원가입</h1> 
	<form method="POST"> 
		{% csrf_token %} 
		{% bootstrap_form form %} 
	<input type="submit" class="btn btn-primary" value="Sign Up"> 
	</form> 
</div> 
{% endblock %}

borameboard/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Borame Board</title>

</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">LOGO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'borame_board:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Menu1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Menu2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'borame_board:index' %}">borameBoard</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        <div>
            <h3><a href="../accounts/signup">회원가입</a></h3>
            <h3><a href="../accounts/login">로그인</a></h3>
            <h3><a href="../accounts/logout">로그아웃</a></h3>
        </div>
        
        {% block content %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

borameboard/templates/borameboard/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 세부 내용</h3>
        </div>
    </div>
    <div class="row my-3">
        <table class="table table-bordered">
            <tr>
                <td>[글 제목] : {{ board_list.title }}</td>
            </tr>
            <tr>
                <td>
                    <p>[글 내용]</p>
                    {{ board_list.content|linebreaks }}
                    <p><small style="color:silver;text-align:right;">[{{ board_list.published_date|date:"Y-m-d H:i:s" }}]</small></p>
                </td>
            </tr>
        </table>
    </div>
    <div style="padding: 2px 20px; float:right;">
        <a href="{% url 'borame_board:index' %}" class="btn btn-primary">글 목록</a>
    </div>
</div>

{% endblock %}

borameboard/templates/borameboard/edit_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 수정</h3>
        </div>
    </div>
    <div class="row my-3"></div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="padding: 5px 50px; float:right;">
                <input class="btn btn-primary" type="submit" value="글 수정">
                <a href="{% url 'borame_board:index' %}" class="btn btn-primary">글 목록</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

borameboard/templates/borameboard/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            
            <h3> 게시판</h3>
        
            <h6>{{user}}님 환영합니다 !</h6>
 

            
        </div>
    </div>
    <div class="row my-3">
        <table class="table table-hover table-bordered">
            <thead>
                <th>No</th>
                <th>제목</th>
                <th>작성자</th>
                <th>내용</th>
                <th>발행일</th>
                <th>비고</th>
            </thead>
            <tbody>
                {% for post in board_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'borame_board:detail' post.id %}">{{ post.title }}</a></td>
                    <td width="100">{{ post.author }}</td>
                    <td>{{ post.content|truncatewords:5 }}</td>
                    <td>{{ post.published_date|date:"Y-m-d" }}</td>
                    <td width="120">
                        <a href="{% url 'borame_board:edit' post.id %}" class="btn btn-outline-info btn-sm">수정</a> 
                        <a href="{% url 'borame_board:delete' post.id %}" onclick="if(!confirm('정말 삭제하시겠습니까?')){return false;}" 
                        class="btn btn-outline-danger btn-sm">삭제</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-md-12 ">
            <a href="{% url 'borame_board:regist' %}" class="btn btn-outline-secondary">글 등록</a>
        </div>
    </div>

    <!-- 페이징 처리 --->
    <div class="row my-3">
        <div class="col-md-12 text-center">
            {% if board_list.has_previous %}
                <a href="?page=1">처음</a>
                <a href="?page={{ board_list.previous_page_number }}">이전</a>
            {% endif %}
                <!-- 페이지리스트 -->
                <span style="color:red;font-weight:bold;">{{ board_list.number }}</span> 
                <span> / </span>
                <span style="font-weight:bold;">{{ board_list.paginator.num_pages }}</span>
            {% if board_list.has_next %}
                <a href="?page={{ board_list.next_page_number }}">다음</a>
                <a href="?page={{ board_list.paginator.num_pages }}">끝</a>
            {% endif %}            

        </div>
    </div>
</div>

{% endblock %}

borameboard/templates/borameboard/regist_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 등록</h3>
        </div>
    </div>
    <div class="row my-3"></div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="padding: 5px 50px; float:right;">
                <input class="btn btn-primary" type="submit" value="글 등록">
                <a href="#" class="btn btn-primary">글 목록</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}